<div class="section widget-blog-posts-grid-default margin_item--<?= /*@noEscape*/ $block->getDataWidgetConfig('space_between_item') ?> image_hover_effects--<?= /*@noEscape*/ $block->getDataWidgetConfig('image_hover_effects') ?>">
	<?php if($block->getDataWidgetConfig('title') != '' || $block->getDataWidgetConfig('short_description') != ''){ ?>
	<div class="elementor__header">
		<?php if($block->getDataWidgetConfig('title') != ''){ ?>
		<h3 class="elementor__headline"><?= $block->escapeHtml($block->getDataWidgetConfig('title')) ?></h3>
		<?php } ?>
		<?php if($block->getDataWidgetConfig('short_description') != ''){ ?>
		<div class="elementor__description"><?= $block->filterOutputContent($block->getDataWidgetConfig('short_description')) ?></div>
		<?php } ?>
	</div>
	<?php } ?>
	<?php $_postCollection = $block->getPostCollection(); ?>
	<?php if ($_postCollection->count()) { ?>
	<div class="elementor__content widget-blog-post-grid">
		<?php $data_sizes = $block->getSizeThumbnail(); ?>
		<?php $items = 0; foreach ($_postCollection as $_post) { $items ++; ?>
		<?php
            $_postUrl = $block->escapeUrl($_post->getPostUrl());
            $_postName = $block->escapeHtml($_post->getTitle());
        ?>
		<div class="elementor-blog-post-item">
			<?php
			$featuredImage = $_post->getFeaturedListImage() ?: $_post->getFeaturedImage();
			$width = 680;
			$height = 450;
            if(isset($data_sizes['common']['img'])){
            	$width = $data_sizes['common']['img']['width'];
            	$height = $data_sizes['common']['img']['height'];
            }
            if($items == 1){
            	if(isset($data_sizes['custom']['img1'])){
            		$width = $data_sizes['custom']['img1']['width'];
            		$height = $data_sizes['custom']['img1']['height'];
            	}
            }
            else{
            	if(isset($data_sizes['custom']['img2'])){
            		$width = $data_sizes['custom']['img2']['width'];
            		$height = $data_sizes['custom']['img2']['height'];
            	}
            }
            if (!$featuredImage) {
            	$featuredImage = '//placehold.jp/1aada3/fff/'.$width.'x'.$height.'.png?text=Minimog';
            }
            $aspect_ratio = $width / $height;
            ?>
			<div class="post-image elementor__item--hover">
				<div class="data-bgset-image-wrapper lazyload" data-bgset="<?= $block->escapeHtml($featuredImage) ?>" data-sizes="auto" style="--aspect-ratio: <?= $aspect_ratio;?>;">
					<a class="item-link" href="<?= /*@noEscape*/ $_postUrl ?>"></a>
				</div>
			</div>
			<div class="post-content">
				<div class="post-info">
					<?php if ($_categoriesCount = $_post->getCategoriesCount()) { ?>
					<div class="post-tags-info">
						<?php $n = 0;
						foreach ($_post->getParentCategories() as $ct) { $n++; ?>
							<a title="<?= $block->escapeHtml($ct->getTitle()) ?>"
								href="<?= $block->escapeUrl($ct->getCategoryUrl()) ?>">
								<?= $block->escapeHtml($ct->getTitle()) ?>
							</a>
							<?php if ($n != $_categoriesCount) { ?>, <?php } ?>
						<?php } ?>
					</div>
					<?php } ?>
					<h3 class="post-title"><a href="<?= /*@noEscape*/ $_postUrl ?>"> <?= /*@noEscape*/ $_postName ?> </a></h3>
					<div class="item post-date">
						<span class="label on-post-date"><?= $escaper->escapeHtml(__('on')) ?></span>
						<span class="value date"><?= $block->escapeHtml(date('F',strtotime($_post->getPublishDate()))) ?> <?= $block->escapeHtml(date('d',strtotime($_post->getPublishDate()))) ?>, <?= $block->escapeHtml(date('Y',strtotime($_post->getPublishDate()))) ?></span>
					</div>	
					<div class="post-description">
						<?= /*@noEscape*/ $block->getShorContent($_post) ?>
					</div>
					<a class="btn post-read-more" href="<?= /*@noEscape*/ $_postUrl ?>"> <?= /*@noEscape*/ __('Read More') ?> </a>
				</div>
			</div>
		</div>
	<?php } ?>
	</div>
	<?php }else{ ?>
	<div class="message info empty">
        <div><?= $escaper->escapeHtml(__('No blog posts were found matching your condition.')) ?></div>
    </div>
	<?php } ?>
</div>