<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Form\Login\Info $block */
?>
<?php if ($block->getRegistration()->isAllowed()) : ?>
<div class="block block-new-customer">
    <div class="block-title">
        <strong id="block-new-customer-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Create an Account')) ?></strong>
    </div>
    <div class="block-content" aria-labelledby="block-new-customer-heading">
    <div class="hotline"><?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('default_newcustomer_benefit')->toHtml(); ?></div>
        <div class="actions-toolbar">
            <div class="primary">
                <a href="<?= $block->escapeUrl($block->getCreateAccountUrl()) ?>" class="action create primary"><span><?= $block->escapeHtml(__('Create an Account')) ?></span></a>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
