<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php
// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Generic.WhiteSpace.ScopeIndent

/** @var \Magento\Catalog\Pricing\Render\PriceBox $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

/** @var \Magento\Catalog\Pricing\Price\TierPrice $tierPriceModel */
$tierPriceModel = $block->getPrice();
$tierPrices = $tierPriceModel->getTierPriceList();
$msrpShowOnGesture = $block->getPriceType('msrp_price')->isShowPriceOnGesture();
$product = $block->getSaleableItem();
?>
<?php if (count($tierPrices)): ?>
    <div class="quantity-discount-hook mt-5 mb-5">
        <h3 class="medium fs_20"><?= $block->escapeHtml(__('Buy more save more!')) ?></h3>
        <ul class="<?= $block->escapeHtmlAttr(($block->hasListClass() ? $block->getListClass() : 'prices-tier items')) ?> radius_as_form bg-white">
            <?php foreach ($tierPrices as $index => $price): ?>
                <li class="item">
                    <?php
                    $isSaleable = $product->isSaleable();
                    if ($isSaleable) {
                        $priceAmountBlock = $block->renderAmount(
                            $price['price'],
                            [
                                'price_id'          => $index,
                                'id_suffix'         => '-' . $index,
                                'include_container' => true,
                                'zone' => \Magento\Framework\Pricing\Render::ZONE_ITEM_OPTION
                            ]
                        );
                        if ($price['percentage_value']) {
                            $priceAmountBlock = $price['percentage_value'].'%';
                        }
                        if ($price['price_qty'] > 1) {
                            $item = __('%1 item(s) get %2 OFF', $price['price_qty'], $priceAmountBlock);
                        } else {
                            $item = __('%1 item get %2 OFF', $price['price_qty'], $priceAmountBlock);
                        }
                        ?>
                        <div class="flex-layout space-between center_vertical">
                            <div class="quantity-tier-product-info">
                                <h4 class="margin_0 medium"><?= $item ?></h4>
                                <p class="margin_0"><?= $block->escapeHtml(__('on each product')) ?></p>
                            </div>
                            <div class="button_action">
                                <button class="action tier-addcart" data-quantity="<?= $price['price_qty'] ?>">
                                    <span><?= $block->escapeHtml(__('Add')) ?></span>
                                </button>
                            </div>
                        </div>
                    <?php } ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
