<img class="photo image lazyload <?= $escaper->escapeHtmlAttr($block->getClass()) ?>"
    data-src="<?= $escaper->escapeUrl($block->getImageUrl()) ?>"
    src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII="
    loading="lazy"
    width="<?= $escaper->escapeHtmlAttr($block->getWidth()) ?>"
    height="<?= $escaper->escapeHtmlAttr($block->getHeight()) ?>"
    alt="<?= $escaper->escapeHtmlAttr($block->getLabel()) ?>" />
