<div class="section widget-category-thumbnail-image category-grid-3 margin_item--<?= /*@noEscape*/ $block->getDataWidgetConfig('space_between_item') ?> image_hover_effects--<?= /*@noEscape*/ $block->getDataWidgetConfig('image_hover_effects') ?>">
	<?php if($block->getDataWidgetConfig('title') != '' || $block->getDataWidgetConfig('short_description') != ''){ ?>
	<div class="elementor__header">
		<?php if($block->getDataWidgetConfig('title') != ''){ ?>
		<h3 class="elementor__headline"><?= $block->escapeHtml($block->getDataWidgetConfig('title')) ?></h3>
		<?php } ?>
		<?php if($block->getDataWidgetConfig('short_description') != ''){ ?>
		<div class="elementor__description"><?= $block->filterOutputContent($block->getDataWidgetConfig('short_description')) ?></div>
		<?php } ?>
	</div>
	<?php } ?>
	<?php $_catCollection = $block->getCatCollection(); ?>
	<?php if ($_catCollection->count()) { ?>
	<div class="row elementor__content">
		<?php $items = 0; foreach ($_catCollection as $_cat) { 
			$items ++;
			$col = 'col-12';
			$width = 1170;
			$height = 600;
			$total_cat = $_catCollection->count();
			if($total_cat == 2){
				$col = 'col-md-6 col-12';
				$width = 570;
				$height = 300;
			}
			if($total_cat == 3){
				if($items == 1){
					$col = 'col-6';
					$width = 570;
					$height = 630;
				}
				else{
					$col = 'col-12';
					$width = 570;
					$height = 300;
				}
			}
			if($total_cat == 4){
				if($items == 1){
					$col = 'col-12';
					$width = 570;
					$height = 505;
				}
				else if($items == 2){
					$col = 'col-12';
					$width = 570;
					$height = 315;
				}
				else if($items == 3){
					$col = 'col-12';
					$width = 570;
					$height = 410;
				}
				else{
					$col = 'col-12';
					$width = 570;
					$height = 410;
				}
			}
		?>
		<?php if($total_cat == 3 && $items == 2){ echo '<div class="col-sm-6 has-children"><div class="row row-level-2">'; } ?>
		<?php if(($total_cat == 4 && $items == 1) || ($total_cat == 4 && $items == 3)){ echo '<div class="col-sm-6 has-children"><div class="row row-level-2">'; } ?>
		<div class="<?= $col ?>">
			<div class="elementor-category-thumbnail-image-item elementor__item--hover">
				<?php
					$featuredImage = '';
					if($_cat->getData('widget_category_thumbnail') != ''){
						$featuredImage = $block->getCategoryThumnnail($_cat->getData('widget_category_thumbnail'));
					}
					if (!$featuredImage) {
						$featuredImage = '//placehold.jp/1aada3/fff/'.$width.'x'.$height.'.png?text='.$width.'x'.$height;
					}
					$aspect_ratio = $width / $height;
				?>
				<a href="<?= /*@noEscape*/ $_cat->getUrl(); ?>" class="category-thumbnail__image data-bgset-image-wrapper lazyload" style="--aspect-ratio: <?= $aspect_ratio;?>;" data-bgset="<?= $block->escapeHtml($featuredImage) ?>" data-sizes="auto">
				</a>
				<div class="category-thumbnail__info absolute center-bottom">
					<h3 class="category-thumbnail__title"><a class="btn category-thumbnail__title_as_button" href="<?= /*@noEscape*/ $_cat->getUrl(); ?>"> <?= /*@noEscape*/ $_cat->getName(); ?> </a></h3>
				</div>
			</div>
		</div>
		<?php if(($total_cat == 3 && $items == 3) || ($total_cat == 4 && $items == 4) || ($total_cat == 4 && $items == 2)){ echo '</div></div>'; } ?>
		<?php if($items == 4){ break; } ?>
		<?php } ?>
	</div>
	<?php }else{ ?>
		<div class="row elementor__content">
			<div class="col-sm-6 has-children">
				<div class="row row-level-2">
					<div class="col-12">
						<div class="elementor-category-thumbnail-image-item elementor__item--hover">
							<a href="#" class="category-thumbnail__image data-bgset-image-wrapper lazyload" style="--aspect-ratio: 1.12871;" data-bgset="//blueskytechmage.com/place_holder/kalles/place_holder-cloth_1.png" data-sizes="auto">
							</a>
							<div class="category-thumbnail__info absolute center-bottom">
								<h3 class="category-thumbnail__title"><a href="#"> Women </a></h3>
							</div>
						</div>
					</div>
					<div class="col-12">
						<div class="elementor-category-thumbnail-image-item elementor__item--hover">
							<a href="#" class="category-thumbnail__image data-bgset-image-wrapper lazyload" style="--aspect-ratio: 1.80952;" data-bgset="//blueskytechmage.com/place_holder/kalles/place_holder-backpack_1.png" data-sizes="auto"> </a>
							<div class="category-thumbnail__info absolute center-bottom">
								<h3 class="category-thumbnail__title"><a href="#"> Accessories </a></h3>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-sm-6 has-children">
				<div class="row row-level-2">
					<div class="col-12">
						<div class="elementor-category-thumbnail-image-item elementor__item--hover">
							<a href="#" class="category-thumbnail__image data-bgset-image-wrapper lazyload" style="--aspect-ratio: 1.39024;" data-bgset="//blueskytechmage.com/place_holder/kalles/place_holder-shoes_1.png" data-sizes="auto"> </a>
							<div class="category-thumbnail__info absolute center-bottom">
								<h3 class="category-thumbnail__title"><a href="#"> Footwear </a></h3>
							</div>
						</div>
					</div>
					<div class="col-12">
						<div class="elementor-category-thumbnail-image-item elementor__item--hover">
							<a href="#" class="category-thumbnail__image data-bgset-image-wrapper lazyload" style="--aspect-ratio: 1.39024;" data-bgset="//blueskytechmage.com/place_holder/kalles/place_holder-watch_1.png" data-sizes="auto">
							</a>
							<div class="category-thumbnail__info absolute center-bottom">
								<h3 class="category-thumbnail__title"><a href="#"> Watches </a></h3>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

	<?php } ?>
</div>