<?php if($block->getConfigNewlltes() > 0 && $block->getContentSetting()){ ?>
<div id="newsletter-popup-common" class="bg-white mfp-hide radius_as_form" data-show="<?= $block->getConfigNewlltes(); ?>" data-width="<?= $block->getConfigNewlltesWidth(); ?>">
	<div class="bls_popup-content newsletter-popup__container radius_as_form">
		<?= $block->getContentSetting() ;?>
		<div class="popup-new__checkzone text-center pb-4 mb-3">
			<input type="checkbox" id="new_check--show">
			<label for="new_check--show"><?= __('Do not show it anymore.');?></label>
		</div>
	</div>
</div>
<?php } ?>
<?php if((!$block->getConfigNewlltes() || $block->getConfigNewlltes() == 0) && $block->getConfigProductPopup() > 0 && $block->getproductsContentSetting()){ ?>
<div id="products-popup-common" class="bg-white mfp-hide" data-show="<?= $block->getConfigProductPopup(); ?>" data-width="<?= $block->getConfigProductPopupWidth(); ?>" data-timeout="<?= $block->getConfigProductPopupTimeout(); ?>">
	<div class="products-popup__container">
		<?= $block->getproductsContentSetting() ;?> 
	</div>
</div>
<?php } ?>