<div class="section widget-testimonial widget-testimonial-slider-default margin_item--<?= /*@noEscape*/ $block->getDataWidgetConfig('margin_item') ?> image_hover_effects--<?= /*@noEscape*/ $block->getDataWidgetConfig('image_hover_effects') ?>">
	<?php if($block->getDataWidgetConfig('title') != '' || $block->getDataWidgetConfig('short_description') != ''){ ?>
	<div class="elementor__header">
		<?php if($block->getDataWidgetConfig('title') != ''){ ?>
		<h3 class="elementor__headline"><?= $block->escapeHtml($block->getDataWidgetConfig('title')) ?></h3>
		<?php } ?>
		<?php if($block->getDataWidgetConfig('short_description') != ''){ ?>
		<div class="elementor__description"><?= $block->filterOutputContent($block->getDataWidgetConfig('short_description')) ?></div>
		<?php } ?>
	</div>
	<?php } ?>
	<?php $testimonials = $block->getTestimonials(); ?>
	<?php if ($testimonials->count()) { ?>
	<div class="elementor__content widget-testimonial-slider">
		<?php foreach ($testimonials as $testimonial){ ?>
			<div class="elementor-testimonial-item elementor__item--hover">
				
				<div class="testimonial-text">
					<div class="testimonial-rating mb-5">
						<div class="rating-summary d-flex justify-content-center">
							<span class="rating-result" style="display:block;">
								<span style="display:block; width:<?php echo $testimonial->getData('rating_summary')*20; ?>%;" class="rating"></span>
							</span>
						</div>
					</div>
					
					<div class="testimonial-content mb-6"><?= $this->escapeHtml($testimonial->getText()); ?></div>
					<div class="testimonial-job d-flex justify-content-center align-items-center">
						<span class="testimonial-name"><?= $this->escapeHtml($testimonial->getName()); ?></span>
						<span class="testimonial-customer d-none">
							<img class="avatar" src="<?= $this->escapeUrl($this->getImage($testimonial))?>" alt="<?php echo __($this->escapeHtml($testimonial->getName())) ?>" title="<?php echo __($this->escapeHtml($testimonial->getName())) ?>" />
						</span>
						<span class="tm-testimonial__position"><?= $testimonial->getJob(); ?></span>
					</div>
					
				</div>
			</div>
		<?php } ?>
	</div>

	<?php }else{ ?>
	<div class="section widget-testimonial widget-testimonial-slider-default">
		<div class="elementor__content widget-testimonial-slider">
			<div class="elementor-testimonial-item elementor__item--hover">
				<div class="testimonial-text">
					<div class="testimonial-rating mb-5">
						<div class="rating-summary d-flex justify-content-center">
							<span class="rating-result" style="display:block;">
								<span style="display:block; width:100%;" class="rating"></span>
							</span>
						</div>
					</div>
					<div class="testimonial-content mb-6">The theme is beautiful. Just got a compliment on it today. The customer service </div>
					<div class="testimonial-job d-flex justify-content-center align-items-center">
						<span class="testimonial-name">alex</span>
						<span class="testimonial-customer d-none">
							<img style="width:50px" class="avatar" src="//blueskytechmage.com/place_holder/kalles/place_holder-backpack_1.png" alt="alex" title="alex" />
						</span>
						<span class="tm-testimonial__position">, California</span>
					</div>
				</div>
			</div>
			<div class="elementor-testimonial-item elementor__item--hover">
				<div class="testimonial-text">
					<div class="testimonial-rating mb-5">
						<div class="rating-summary d-flex justify-content-center">
							<span class="rating-result" style="display:block;">
								<span style="display:block; width:100%;" class="rating"></span>
							</span>
						</div>
					</div>
					<div class="testimonial-content mb-6">The theme is beautiful. Just got a compliment on it today. The customer service </div>
					<div class="testimonial-job d-flex justify-content-center align-items-center">
						<span class="testimonial-name">alex</span>
						<span class="testimonial-customer d-none">
							<img style="width:50px" class="avatar" src="//blueskytechmage.com/place_holder/kalles/place_holder-backpack_1.png" alt="alex" title="alex" />
						</span>
						<span class="tm-testimonial__position">, California</span>
					</div>
				</div>
			</div>
			<div class="elementor-testimonial-item elementor__item--hover">
				<div class="testimonial-text">
					<div class="testimonial-rating mb-5">
						<div class="rating-summary d-flex justify-content-center">
							<span class="rating-result" style="display:block;">
								<span style="display:block; width:100%;" class="rating"></span>
							</span>
						</div>
					</div>
					<div class="testimonial-content mb-6">The theme is beautiful. Just got a compliment on it today. The customer service </div>
					<div class="testimonial-job d-flex justify-content-center align-items-center">
						<span class="testimonial-name">alex</span>
						<span class="testimonial-customer d-none">
							<img style="width:50px" class="avatar" src="//blueskytechmage.com/place_holder/kalles/place_holder-backpack_1.png" alt="alex" title="alex" />
						</span>
						<span class="tm-testimonial__position">, California</span>
					</div>
				</div>
			</div>
		</div>
	</div>

	<?php } ?>
</div>