<?php
use Magento\Framework\App\Action\Action;

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */

// phpcs:disable Generic.Files.LineLength.TooLong
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper
?>
<?php
$type = 'widget-product-grid';

$mode = 'grid';

$image = 'new_products_content_widget_grid';

$showWishlist = true;
$showCompare = true;
$showCart = true;
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$description = false;
?>
<div class="block widget block-products-list <?= /* @noEscape */ $mode ?>">
    <?php if ($block->getTitle()): ?>
        <div class="block-title">
            <strong><?= $block->escapeHtml(__($block->getTitle())) ?></strong>
        </div>
    <?php endif ?>
    <?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
        <?php
            $items = $block->getProductCollection()->getItems();
        ?>
        <div class="block-content">
            <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
            <div class="products-<?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $mode ?>">
                <ol class="product-items <?= /* @noEscape */ $type ?>">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <?= /* @noEscape */ ($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                        <div class="product-item-info">
                            <div class="product_item_images">
                                <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product-item-photo">
                                    <?= $block->getImage($_item, $image)->toHtml() ?>
                                </a>
                                <?php if ($showWishlist || $showCompare || $showCart): ?>
                                    <div class="product-item-inner">
                                        <div class="product-item-actions">
                                            <div class="product-item-actions_middle">
                                                <?php if ($showCart): ?>
                                                    <div class="actions-primary">
                                                        <?php if ($_item->isSaleable()): ?>
                                                            <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                                            <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_item->getSku()) ?>" action="<?= $block->escapeUrl($postParams['action']) ?>" method="post">
                                                                <input type="hidden" name="product" value="<?= $block->escapeHtmlAttr($postParams['data']['product']) ?>">
                                                                <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                                <?= $block->getBlockHtml('formkey') ?>
                                                                <button type="submit"
                                                                        title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                                        class="action tocart primary">
                                                                    <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                                </button>
                                                            </form>
                                                        <?php else: ?>
                                                            <?php if ($_item->isAvailable()): ?>
                                                                <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                                            <?php else: ?>
                                                                <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                                            <?php endif; ?>
                                                        <?php endif; ?>
                                                    </div>
                                                <?php endif; ?>
                                            </div>
                                            <?php if ($showWishlist || $showCompare): ?>
                                                <div class="actions-secondary" data-role="add-to-links">
                                                    <?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist): ?>
                                                        <a href="#"
                                                            data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>' class="action towishlist" data-action="add-to-wishlist" title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                            <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                    <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                        <?php $compareHelper = $this->helper(\Magento\Catalog\Helper\Product\Compare::class);?>
                                                        <a href="#" class="action tocompare" data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_item) ?>' title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                                                            <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                <?php endif; ?>
                            </div>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                        href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                        class="product-item-link">
                                        <?= $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>
                                <?php if ($templateType): ?>
                                    <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                <?php endif; ?>

                                <?= $block->getProductPriceHtml($_item, $type) ?>

                                <?= $block->getProductDetailsHtml($_item) ?>
                            </div>
                        </div>
                        <?= ($iterator == count($items) + 1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
            <?= $block->getPagerHtml() ?>
        </div>
        <?php if($block->getBlockHtml('formkey')): ?>
        <script type="text/x-magento-init">
        {
            ".block.widget [data-role=tocart-form]": {
                "Magento_Catalog/js/validate-product": {}
            }
        }
        </script>
        <?php endif;?>
    <?php else: ?>
        <div class="block-content">
            <div class="products-grid grid">
                <ol class="product-items widget-product-grid">
                    <li class="product-item">
                        <div class="product-item-info">
                            <div class="product_item_images">
                                <a href="#" class="product-item-photo">
                                    <span class="product-image-container product-image-container-23" style="width: 700px;" data-hover="image_hover_effects--zoom-overlay">
                                        <span class="product-image-wrapper" style="padding-bottom: 127.42857142857%;">
                                            <img class="product-image-photo lazyload" data-src="//blueskytechmage.com/place_holder/kalles/place_holder-shoes_1.png" src="//blueskytechmage.com/place_holder/kalles/place_holder-shoes_1.png" loading="lazy" width="700" height="892" alt="Black mountain hat" />
                                        </span>
                                    </span>
                                </a>
                                <div class="product-item-inner">
                                    <div class="product-item-actions">
                                        <div class="product-item-actions_middle">
                                            <div class="actions-primary">
                                                <button type="submit" title="Add to Cart" class="action tocart primary">
                                                    <span>Add to Cart</span>
                                                </button>
                                            </div>
                                        </div>
                                        <div class="actions-secondary" data-role="add-to-links">
                                            <a href="#" class="action towishlist" data-action="add-to-wishlist" title="Add to Wish List">
                                                <span>Add to Wish List</span>
                                            </a>
                                            <a href="#" class="action tocompare" title="Add to Compare">
                                                <span>Add to Compare</span>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a title="Black mountain hat" href="#" class="product-item-link"> Black mountain hat </a>
                                </strong>
                                <div class="product-reviews-summary short">
                                    <div class="rating-summary">
                                        <div class="rating-result" title="93%">
                                            <span style="width: 93%;"><span>93%</span></span>
                                        </div>
                                    </div>
                                </div>

                                <div class="price-box price-final_price">
                                    <span class="price">$15.00</span>
                                </div>
                            </div>
                        </div>
                    </li>
                </ol>
            </div>
        </div>

    <?php endif;?>
</div>
