<div id="locator_filter-store" class="block row gx-5">
    <div class="column_left col-md-4">
		<div class="center"> 
			<div class="store_list"><?= $block->getChildHtml('store_list_view') ?></div>
		</div>
    </div>
	<div class="column_right col-md-8">
		 <div id="bst-map-view" style="height: 100%"></div>
    </div>
</div>
<script language="javascript" type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=<?php echo $block->getApiKey() ?>&libraries=places"></script>
<script>
    var baloonTemplate = <?php echo $block->getBaloonTemplate() ?>;
</script>
<script>
    require([
        'jquery',
        'Blueskytechco_StoreLocator/js/viewmap',
        'Blueskytechco_StoreLocator/js/cluster',
        'domReady!'
    ], function ($) {
        $('#bst-map-view').bstLocatorView({
            jsonLocations: <?php echo $this->getJsonLocations() ?>,
			imageShop: "<?php echo $block->getViewFileUrl('Blueskytechco_StoreLocator::images/shop.jpg'); ?>",
            imageLocations: "<?php echo $block->getViewFileUrl('Blueskytechco_StoreLocator::images/'); ?>"
        })
    });
</script>



