<?php
/**
 * Vertical Menu for store
 *
 * @var $viewModel \Blueskytechco\MenuBuilder\ViewModel\MenuBuilder
 */
?>
<?php
    $view_model = $viewModel;
    $animation = $view_model->getData('menus/vertical/animation');
    $active_menu_config = $view_model->getData('menus/vertical/active');
    $limit_show = $view_model->getData('menus/vertical/limit_show')
        ? $view_model->getData('menus/vertical/limit_show')
        : 10;
    $show_screen = $view_model->getData('menus/vertical/show_screen');
    $small_desktop = ($show_screen && $view_model->getData('menus/vertical/small_desktop'))
        ? $view_model->getData('menus/vertical/small_desktop')
        : $limit_show;
    $tablet = ($show_screen && $view_model->getData('menus/vertical/tablet'))
        ? $view_model->getData('menus/vertical/tablet')
        : $limit_show;
    $mobile = ($show_screen && $view_model->getData('menus/vertical/mobile'))
        ? $view_model->getData('menus/vertical/mobile')
        : $limit_show;
    $id_menu = $block->getData('menus_select');
if (!$active_menu_config && $view_model->getWidgetMenuHtml($id_menu)) {
    ?>
<div class="vertical-menu-container navigation">
    <div data-action="toggle-nav" class="action nav-toggle d-xl-none sticky-toggle">
        <span><?= $block->escapeHtml(__('Toggle Nav')) ?></span>
    </div>
    <?php if ($block->getData('title')) {?>
        <h3 class="title-menu-dropdown active">
            <?= $block->escapeHtml($block->getData('title'));?>
        </h3>
    <?php } ?>
    <div class="navigation nav-sections">
        <div class="close-menu-mobile d-block d-xl-none">
            <a href="#" class="close-menu"><?= $block->escapeHtml(__('Close')) ?></a>
        </div>
        <?php if ($block->getData('title')) {?>
            <div class="menu-mobile-title d-block d-xl-none">
                <span><?= $block->escapeHtml($block->getData('title'));?></span>
            </div>
        <?php } ?>
        <div class="verticalmenu-html">
            <ul class="verticalmenu-list <?= $block->escapeHtml($animation) ?>">  
                <?= $view_model->getWidgetMenuHtml($id_menu) ?>
                <li class="expand-menu-link level0">
                    <a href="javascript:void(0);" class="level-top"><?= $block->escapeHtml(__('More Menus')) ?></a>
                </li> 
            </ul>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        ".vertical-menu-container": {
            "Blueskytechco_MenuBuilder/js/components/verticalmenu": {
                "limitShow":"<?= $block->escapeHtml($limit_show) ?>",
                "smallDesktop":"<?= $block->escapeHtml($small_desktop) ?>"     
            }
        }
    }
</script>
<?php } ?>
