<?php
/**
 * Horizontal menu for store
 *
 * @var $viewModel \Blueskytechco\MenuBuilder\ViewModel\MenuBuilder
 */
?>
<?php
    $view_model = $block->getViewModel();
    $animation = $view_model->getData('menus/horizontal/animation');
if ($view_model->getHorizontalMenuHtml()) {
    ?>
<div class="horizontal-menu-container">
    <div data-action="toggle-nav" class="action nav-toggle d-xl-none sticky-toggle">
        <svg width="22px" height="22px" fill="currentColor" stroke="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
            <path d="M442 114H6a6 6 0 0 1-6-6V84a6 6 0 0 1 6-6h436a6 6 0 0 1 6 6v24a6 6 0 0 1-6 6zm0 160H6a6 6 0 0 1-6-6v-24a6 6 0 0 1 6-6h436a6 6 0 0 1 6 6v24a6 6 0 0 1-6 6zm0 160H6a6 6 0 0 1-6-6v-24a6 6 0 0 1 6-6h436a6 6 0 0 1 6 6v24a6 6 0 0 1-6 6z"></path>
        </svg>
    </div>
    <nav class="navigation horizontal main-nav nav-sections">
        <div class="close-menu-mobile">
            <a href="#" class="close-menu"><?= $block->escapeHtml(__('Close')) ?></a>
        </div>
        <div class="mobile-menu-content">
            <div class="menu-mobile-title d-block d-xl-none">
                <a class="active" data-menu="horizontal-list" href="#"> 
                    <span><?= $block->escapeHtml(__('Menu')) ?></span>
                </a>
            </div>
            <ul class="horizontal-list menu <?= $block->escapeHtml($animation) ?>">
                <?= $view_model->getHorizontalMenuHtml() ?>
            </ul>
        </div>
    </nav>
</div>
<script type="text/x-magento-init">
    {
        ".horizontal-menu-container": {
            "Blueskytechco_MenuBuilder/js/components/horizontalmenu": {}
        }
    }
</script>
<?php } ?>