<?php
use Magento\Framework\App\Action\Action;

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
/** @var \Magento\Catalog\Helper\Output $_helper */
$_helper = $block->getData('outputHelper');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?= $escaper->escapeHtml(__('We can\'t find products matching the selection.')) ?></div>
    </div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() === 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
        <ol class="products list items product-items container-products-packery">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php 
                $i = 1;
                $rows = 2;
                $col = 3;
            ?>
            <?php foreach ($_productCollection as $_product): ?>
            <?php 
                if ($i % $rows == 0) {
                    $rows = $rows + 8;
                    $col = 6;
                } else {
                    $col = 3;
                }
            ?>
            <li class="col-lg-<?= /* @noEscape */ $col ?> col-md-3 col-sm-6 item product product-item">
                <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                <div class="product-item-info image_hover_effects--zoom"
                     id="product-item-info_<?= /* @noEscape */ $_product->getId() ?>"
                     data-container="product-<?= /* @noEscape */ $viewMode ?>">
                    <?php
                    $productImage = $block->getImage($_product, $imageDisplayArea);
                    if ($pos != null) {
                        $position = 'left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;';
                    }
                    ?>
                    <?php // Product Image ?>
                    <div class="product_item_images">
                        <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                        class="product photo product-item-photo"
                        tabindex="-1">
                            <?= $productImage->toHtml() ?>
                        </a>
                        <?php if ($block->getMode() == 'grid') { ?>
                            <div class="product-item-inner">
                                <div class="product actions product-item-actions">
                                    <div class="product-item-actions_middle">
                                        <div class="actions-primary">
                                            <?php if ($_product->isSaleable()):?>
                                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                <form data-role="tocart-form"
                                                    data-product-sku="<?= $escaper->escapeHtml($_product->getSku()) ?>"
                                                    action="<?= $escaper->escapeUrl($postParams['action']) ?>"
                                                    method="post">
                                                    <?php $optionsData = $block->getData('viewModel')->getOptionsData($_product); ?>
                                                    <?php foreach ($optionsData as $optionItem): ?>
                                                        <input type="hidden"
                                                            name="<?= $escaper->escapeHtml($optionItem['name']) ?>"
                                                            value="<?= $escaper->escapeHtml($optionItem['value']) ?>">
                                                    <?php endforeach; ?>
                                                    <input type="hidden"
                                                        name="product"
                                                        value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                                    <input type="hidden"
                                                        name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                                        value="<?=
                                                        /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED]
                                                            ?>">
                                                    <?= $block->getBlockHtml('formkey') ?>
                                                    <button type="submit"
                                                            title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                            class="action tocart primary"
                                                            disabled>
                                                        <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                                    </button>
                                                </form>
                                            <?php else:?>
                                                <?php if ($_product->isAvailable()):?>
                                                    <div class="stock available">
                                                        <span><?= $escaper->escapeHtml(__('In stock')) ?></span></div>
                                                <?php else:?>
                                                    <div class="stock unavailable">
                                                        <span><?= $escaper->escapeHtml(__('Out of stock')) ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                    <?= ($pos && strpos($pos, $viewMode . '-primary')) ?
                                        /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                            $position,
                                            'product-item-info_' . $_product->getId() . ' div.actions-primary'
                                        ) : '' ?>
                                    <div data-role="add-to-links" class="actions-secondary">
                                        <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                            <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                        <?php endif; ?>
                                    </div>
                                    <?= ($pos && strpos($pos, $viewMode . '-secondary')) ?
                                        /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                            $position,
                                            'product-item-info_' . $_product->getId() . ' div.actions-secondary'
                                        ) : '' ?>
                                </div>
                                <?php if ($showDescription): ?>
                                    <div class="product description product-item-description">
                                        <?= /* @noEscape */ $_helper->productAttribute(
                                            $_product,
                                            $_product->getShortDescription(),
                                            'short_description'
                                        ) ?>
                                        <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                                        title="<?= /* @noEscape */ $_productNameStripped ?>"
                                        class="action more"><?= $escaper->escapeHtml(__('Learn More')) ?></a>
                                    </div>
                                <?php endif; ?>
                            </div>
                        <?php } ?>
                    </div>
                    <div class="product details product-item-details">
                        <?php if ($block->getMode() == 'list') { ?><div class="flex-layout no-wrap-desktop space-between center_vertical"><?php } ?>
                            <?php if ($block->getMode() == 'list') { ?> <div class="list-product-infor"><?php } ?>
                                <strong class="product name product-item-name">
                                    <a class="product-item-link"
                                    href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>">
                                        <?=/* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name')?>
                                    </a>
                                </strong>
                                <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                                <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                                <?php if ($showDescription): ?>
                                    <div class="product description product-item-description">
                                        <?= /* @noEscape */ $_helper->productAttribute(
                                            $_product,
                                            $_product->getShortDescription(),
                                            'short_description'
                                        ) ?>
                                        <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                                        title="<?= /* @noEscape */ $_productNameStripped ?>"
                                        class="action more"><?= $escaper->escapeHtml(__('Learn More')) ?></a>
                                    </div>
                                <?php endif; ?>
                                <?= $block->getProductDetailsHtml($_product) ?>
                            <?php if ($block->getMode() == 'list') { ?> </div><?php } ?>
                            <?php if ($block->getMode() == 'list') { ?> 
                                <div class="product-item-inner action-column-right">
                                    <div class="product actions product-item-actions">
                                        <div data-role="add-to-links" class="actions-secondary">
                                            <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                                <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                            <?php endif; ?>
                                        </div>
                                        <?= ($pos && strpos($pos, $viewMode . '-secondary')) ?
                                            /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                                $position,
                                                'product-item-info_' . $_product->getId() . ' div.actions-secondary'
                                            ) : '' ?>
                                        <div class="actions-primary">
                                            <?php if ($_product->isSaleable()):?>
                                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                <form data-role="tocart-form"
                                                    data-product-sku="<?= $escaper->escapeHtml($_product->getSku()) ?>"
                                                    action="<?= $escaper->escapeUrl($postParams['action']) ?>"
                                                    method="post">
                                                    <?php $optionsData = $block->getData('viewModel')->getOptionsData($_product); ?>
                                                    <?php foreach ($optionsData as $optionItem): ?>
                                                        <input type="hidden"
                                                            name="<?= $escaper->escapeHtml($optionItem['name']) ?>"
                                                            value="<?= $escaper->escapeHtml($optionItem['value']) ?>">
                                                    <?php endforeach; ?>
                                                    <input type="hidden"
                                                        name="product"
                                                        value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                                    <input type="hidden"
                                                        name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                                        value="<?=
                                                        /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED]
                                                            ?>">
                                                    <?= $block->getBlockHtml('formkey') ?>
                                                    <button type="submit"
                                                            title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                            class="action tocart primary"
                                                            disabled>
                                                        <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                                    </button>
                                                </form>
                                            <?php else:?>
                                                <?php if ($_product->isAvailable()):?>
                                                    <div class="stock available">
                                                        <span><?= $escaper->escapeHtml(__('In stock')) ?></span></div>
                                                <?php else:?>
                                                    <div class="stock unavailable">
                                                        <span><?= $escaper->escapeHtml(__('Out of stock')) ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                        <?= ($pos && strpos($pos, $viewMode . '-primary')) ?
                                            /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                                $position,
                                                'product-item-info_' . $_product->getId() . ' div.actions-primary'
                                            ) : '' ?>
                                    </div>
                                </div>
                            <?php } ?>
                        <?php if ($block->getMode() == 'list') { ?></div><?php } ?>
                    </div>
                </div>
                <?= ($pos && strpos($pos, $viewMode . '-actions')) ?
                /* @noEscape */ $secureRenderer->renderStyleAsTag(
                    $position,
                    'product-item-info_' . $_product->getId() . ' div.product-item-actions'
                ) : '' ?>
            </li>
            <?php $i++; ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getChildBlock('toolbar')->setIsBottom(true)->toHtml() ?>
    <script type="text/x-magento-init">
    {
        "[data-role=tocart-form], .form.map.checkout": {
            "catalogAddToCart": {
                "product_sku": "<?= $escaper->escapeJs($_product->getSku()) ?>"
            }
        }
    }
    </script>
    <script>
        require([
            'jquery',
            'Blueskytechco_PageBuilderCustom/js/resource/packery/packery.pkgd'
        ], function ($, Packery) {
            require( [ 'jquery-bridget/jquery-bridget' ], function( jQueryBridget ) {
                jQueryBridget('packery', Packery, $);
                $('.products.product-items').packery({
                    itemSelector: '.product-item',
                    columnWidth: '.product-item',
                    gutter: 0,
                    percentPosition: true,
                    originLeft: true 
                });
            });
        });
    </script>
<?php endif; ?>