<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Generic.WhiteSpace.ScopeIndent.IncorrectExact
// phpcs:disable Magento2.Security.LanguageConstruct.DirectOutput
?>
<?php
    $_category  = $block->getCurrentCategory();
    $_class = '';
    if ($_imgUrl = $block->getImage()->getUrl($_category)) {
        $_imgUrl =  " style=\"background-image: url('".$block->escapeUrl($_imgUrl)."');\"";
        $_class = ' background-image';
    }
?>
<div class="category-info<?= $_class ?>" <?= $_imgUrl ?>>
    <div class="category-view-info">
        <?= $block->getChildHtml('page.main.title'); ?>
        <?= $block->getChildHtml('category.description'); ?>
        <?= $block->getChildHtml('category.cms'); ?>
    </div>
</div>
