<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post list item template
 *
 * @var $block \Magefan\Blog\Block\Post\AbstractPost
 */
?>
<?php
$_post = $block->getPost();
$_postUrl = $block->escapeUrl($_post->getPostUrl());
$_postName = $block->escapeHtml($_post->getTitle());
?>
<li class="post-holder post-holder-<?= (int)$_post->getId() ?> image_hover_effects--zoom">
    <div class="post-header">
        <?php $featuredImage = $_post->getFeaturedListImage() ?: $_post->getFeaturedImage(); ?>
        <?php if ($featuredImage) { ?>
            <?php
            $featuredImgAlt = $_post->getData('featured_list_img_alt') ?: $_post->getData('featured_img_alt');
            if (!$featuredImgAlt) {
                $featuredImgAlt = $_postName;
            }
            ?>
            <div class="post-ftimg-hld elementor__item--hover">
                <a href="<?= /*@noEscape*/ $_postUrl ?>"
                    class="post-image-effect"
                    title="<?= /*@noEscape*/ $_postName ?>">
                    <img src="<?= $block->escapeUrl($featuredImage) ?>"
                            alt="<?= $block->escapeHtml($featuredImgAlt) ?>" />
                </a>
            </div>
        <?php } ?>
        <div class="post-info">
            <?php if ($_categoriesCount = $_post->getCategoriesCount()) { ?>
                <div class="item post-categories">
                    <?php $n = 0; ?>
                    <?php foreach ($_post->getParentCategories() as $ct) { ?>
                        <?php $n++; ?>
                        <a title="<?= $block->escapeHtml($ct->getTitle()) ?>"
                        href="<?= $block->escapeUrl($ct->getCategoryUrl()) ?>"
                        ><?= $block->escapeHtml($ct->getTitle()) ?></a><?= /*@noEscape*/ ($n != $_categoriesCount) ? ',' : '' ?>
                    <?php } ?>
                </div>
            <?php } ?>
        </div>
        
        <div class="post-title">
            <a class="post-item-link"
                href="<?= /*@noEscape*/ $_postUrl ?>">
                <?= /*@noEscape*/ $_postName ?>
            </a>
        </div>
    </div>
</li>