<?php
    $_postCollection = $block->getPostCollection();
?>
<?php if ($_postCollection->count()) { ?>
<div class="block-content">
	<div class="blog-list-post-featured slick-slider">
	<?php foreach ($_postCollection as $_post) { ?>
		<?php
			$_postUrl = $block->escapeUrl($_post->getPostUrl());
			$_postName = $block->escapeHtml($_post->getTitle());
		?>
		<div class="item image_hover_effects--zoom clearfix">
			<?php $featuredImage = $_post->getFeaturedListImage() ?: $_post->getFeaturedImage(); ?>
			<?php if ($featuredImage) { ?>
				<div class="post-image elementor__item--hover">
					<?php
					$featuredImgAlt = $_post->getData('featured_list_img_alt') ?: $_post->getData('featured_img_alt');
					if (!$featuredImgAlt) {
						$featuredImgAlt =  $_postName;
					}
					?>
					<a class="post-item-link post-image-effect" title="<?= $_postName ?>" href="<?= $_postUrl ?>">
						<img src="<?= $block->escapeUrl($featuredImage) ?>"
                             alt="<?= $block->escapeHtml($featuredImgAlt) ?>" />
					</a>
				</div>
			<?php } ?>
			<div class="post-top">
                <div class="post-item-title">
                    <a class="post-item-link" title="<?= $_postName ?>" href="<?= $_postUrl ?>">
                        <?= $_postName ?>
                    </a>
                </div>
                <?php if ($featuredImage && $_post->isPublishDateEnabled()) { ?>
                    <div class="post-item-date">
                        <span class="value"><?= $block->escapeHtml($_post->getPublishDate()) ?></span>
                    </div>
                <?php } ?>
			</div>
		</div>
	<?php } ?>
	</div>
</div>
<script> 
    require([
        'jquery',
        'slick'
        ], function ($) {
        'use strict';
        $(document).ready(function() {
            var $carouselElement = $('.blog-list-post-featured'),
            slickConfig = {
                slidesToShow: 3,
                slidesToScroll: 3,
                rows: 1,
                autoplay: false,
                autoplaySpeed: false,
                arrows: true,
                dots: false,
                responsive: [
                {
                    breakpoint: 1400,
                    settings: {
                    slidesToShow: 3,
                    slidesToScroll: 3
                    }
                },
                {
                    breakpoint: 1200,
                    settings: {
                    slidesToShow: 3,
                    slidesToScroll: 3
                    }
                },
                {
                    breakpoint: 992,
                    settings: {
                    slidesToShow: 2,
                    slidesToScroll: 2
                    }
                },
                {
                    breakpoint: 768,
                    settings: {
                    slidesToShow: 2,
                    slidesToScroll: 2
                    }
                },
                {
                    breakpoint: 576,
                    settings: {
                    slidesToShow: 1,
                    slidesToScroll: 1
                    }
                }
                ]
            };
            $carouselElement.slick(slickConfig);
        });
    });
    </script>
<?php } ?>
