<?php
use Magento\Framework\App\Action\Action;
?>
<div class="section widget-product-countdown-timers-grid-default margin_item--<?= /*@noEscape*/ $block->getDataWidgetConfig('space_between_item') ?> desgin_product_price_countdown--<?= /*@noEscape*/ $block->getDataWidgetConfig('desgin') ?> products-grid">
	<?php if($block->getDataWidgetConfig('title') != '' || $block->getDataWidgetConfig('short_description') != ''){ ?>
	<div class="elementor__header">
		<?php if($block->getDataWidgetConfig('title') != ''){ ?>
		<h3 class="elementor__headline"><?= $block->escapeHtml($block->getDataWidgetConfig('title')) ?></h3>
		<?php } ?>
		<?php if($block->getDataWidgetConfig('short_description') != ''){ ?>
		<div class="elementor__description"><?= $block->filterOutputContent($block->getDataWidgetConfig('short_description')) ?></div>
		<?php } ?>
	</div>
	<?php } ?>
	<?php if($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())){ ?>
	<?php
    $type = 'widget-product-countdown-timers-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;
    ?>
	<ol class="elementor__content product-countdown-layout2 row product-items <?= /* @noEscape */ $type ?>">
        <?php $iterator = 1; ?>
        <?php foreach ($items as $_item): ?>
            <?= /* @noEscape */ '<li class="product-item'.$block->getCol().'">' ?>
                <div class="product-item-info">
    				    <div class="product_item-images product_item_images">
                            <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product-item-photo">
                                <?= $block->getImage($_item, $image)->toHtml() ?>
                            </a>
                        </div>
    					<?php if ($showWishlist || $showCompare || $showCart): ?>
                            <div class="product-item-actions">
    							<div class="product-item-actions-middle">
                                    <div class="product_item-details">
                                        <strong class="product-item-name post-title-2-rows">
                                            <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                            href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                            class="product-item-link">
                                                <?= $block->escapeHtml($_item->getName()) ?>
                                            </a>
                                        </strong>
                                        <?= $block->getProductPriceHtml($_item, $type) ?>
                                        <div class="shot-description d-none"> <?= $_item->getShortDescription(); ?></div>
                                       
                                    </div>
                                    <div class="variations_button">   
                                        <?php if ($showCart): ?>
                                            <div class="actions-primary">
                                                <?php if ($_item->isSaleable()): ?>
                                                    <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                                    <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_item->getSku()) ?>" action="<?= $block->escapeUrl($postParams['action']) ?>" method="post">
                                                        <input type="hidden" name="product" value="<?= $block->escapeHtmlAttr($postParams['data']['product']) ?>">
                                                        <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                        <?= $block->getBlockHtml('formkey') ?>
                                                        <button type="submit"
                                                                title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                                class="action tocart primary">
                                                            <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                        </button>
                                                    </form>
                                                <?php else: ?>
                                                    <?php if ($_item->isAvailable()): ?>
                                                        <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>

                                        <?php if ($showWishlist || $showCompare): ?>
                                            <div class="actions-secondarys" data-role="add-to-links">
                                                <?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist): ?>
                                                    <a href="#"
                                                    data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>' class="action towishlist" data-action="add-to-wishlist" title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                        <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                                    </a>
                                                <?php endif; ?>
                                                <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                    <?php $compareHelper = $this->helper(\Magento\Catalog\Helper\Product\Compare::class);?>
                                                    <a href="#" class="action tocompare" data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_item) ?>' title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                                                        <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                                    </a>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                    <div data-countdown="<?= $block->getDataCountdown($_item) ?>"></div>
                                    <div class="final-date-product-countdown-timers"></div>
                                    <div class="product-share-links">
                                        <div class="share-links"><a href="#" class="share-links-click"><?= __('share') ?></a></div>
                                        <div class="share-dialog">
                                            <a href="#" class="my-tooltip-top" onclick=" window.open( 'https://www.facebook.com/sharer/sharer.php?u='+encodeURIComponent(location.href), 'facebook-share-dialog', 'width=436,height=436'); return false;"><span class="icon fab fa-facebook-f"><span class="text tooltip-content no-wrap"><?= $block->escapeHtmlAttr(__('Facebook')) ?></span></span></a>
                                            <a href="#" class="my-tooltip-top" onclick=" window.open( 'http://twitter.com/home/?status='+encodeURIComponent(location.href), 'twitter-share-dialog', 'width=436,height=436'); return false;"><span class="icon fab fa-twitter"><span class="text tooltip-content no-wrap"><?= $block->escapeHtmlAttr(__('Twitter')) ?></span></span></a>
                                            <a href="#" class="my-tooltip-top" onclick=" window.open( 'http://pinterest.com/pin/create/button/?url='+encodeURIComponent(location.href), 'pinterest-share-dialog', 'width=436,height=436'); return false;"><span class="icon fab fa-pinterest"><span class="text tooltip-content no-wrap"><?= $block->escapeHtmlAttr(__('Pinterest')) ?></span></span></a>
                                            <a href="#" class="my-tooltip-top" onclick=" window.open( 'https://plus.google.com/share?url='+encodeURIComponent(location.href), 'twitter-share-dialog', 'width=436,height=436'); return false;"><span class="icon fab fa-google"><span class="text tooltip-content no-wrap"><?= $block->escapeHtmlAttr(__('Google')) ?></span></span></a>
                                        </div>
                                    </div> 
                                </div>
                            </div>
                            <?php endif; ?>

                        <?php endif; ?>
    				   
                </div>
            </li>
        <?php endforeach ?>
    </ol>
	<?php }else{ ?>
        <ol class="elementor__content product-countdown-layout2 row product-items widget-product-countdown-timers-grid">
            <li class="product-item col-xxl-12 col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                <div class="product-item-info">
                    <div class="product_item-images product_item_images">
                        <a href="#" class="product-item-photo">
                            <span class="product-image-container product-image-container-316" style="width: 700px;" data-hover="image_hover_effects--zoom-overlay">
                                <span class="product-image-wrapper" style="padding-bottom: 100%;">
                                    <img
                                        class="product-image-photo lazyload"
                                        data-src="//blueskytechmage.com/place_holder/kalles/place_holder-backpack_1.png"
                                        src="//blueskytechmage.com/place_holder/kalles/place_holder-backpack_1.png"
                                        loading="lazy"
                                        width="700"
                                        height="700"
                                        alt="Orange Asparagus"
                                    />
                                </span>
                                <span class="product-label"> <span class="onsale label-product">33%</span> </span>
                            </span>
                        </a>
                    </div>
                    <div class="product-item-actions">
                        <div class="product-item-actions-middle">
                            <div class="product_item-details">
                                <strong class="product-item-name">
                                    <a title="Orange Asparagus" href="#" class="product-item-link"> Orange Asparagus </a>
                                </strong>
                                <div class="price-box-holder price-final_price">
                                    <span class="special-price">
                                        <span class="price">$40.00</span>
                                    </span>
                                    <span class="old-price">
                                        <span class="price">$60.00</span>
                                    </span>
                                </div>
                                <p>Premium Materials How your food is grown or raised can have a major impact on your mental and emotional health as well as the environment. Organic foods often have more beneficial...</p>
                            </div>
                            <div class="variations_button">
                                <div class="actions-primary">
                                    <button type="submit" title="Add to Cart" class="action tocart primary">
                                        <span>Add to Cart</span>
                                    </button>
                                </div>
                                <div class="actions-secondarys" data-role="add-to-links">
                                    <a href="#" title="Add to Wish List" class="action towishlist">
                                        <span>Add to Wish List</span>
                                    </a>
                                    <a href="#" title="Add to Compare" class="action tocompare">
                                        <span>Add to Compare</span>
                                    </a>
                                </div>
                            </div>
                            <div data-countdown="2024/02/12 23:59:59"></div>
                            <div class="final-date-product-countdown-timers"></div>
                            <div class="product-share-links">
                                <div class="share-links"><a href="#" class="share-links-click">share</a></div>
                                <div class="share-dialog">
                                    <a href="#" class="my-tooltip-top">
                                        <span class="icon fab fa-facebook-f"><span class="text tooltip-content no-wrap">Facebook</span></span>
                                    </a>
                                    <a href="#" class="my-tooltip-top">
                                        <span class="icon fab fa-twitter"><span class="text tooltip-content no-wrap">Twitter</span></span>
                                    </a>
                                    <a href="#" class="my-tooltip-top">
                                        <span class="icon fab fa-pinterest"><span class="text tooltip-content no-wrap">Pinterest</span></span>
                                    </a>
                                    <a href="#" class="my-tooltip-top">
                                        <span class="icon fab fa-google"><span class="text tooltip-content no-wrap">Google</span></span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
        </ol>

	<?php } ?>
</div>