<div class="header-container layout-2 header_style-2 mb-xl-3">
	<?php if($block->isEnableTopBar()){ ?>
	<div class="topbar d-none d-md-block border_bottom">
		<div class="topbar__inner flex-layout space-between center_vertical container-fluid">
			<div class="topbar__section col_left d-none d-xxl-block">
				<div class="topbar__section-inner">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('default_topbar_social')->toHtml(); ?>
				</div>
			</div>
			<div class="topbar__section col_right flex-layout center_vertical flex-end">
				<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('default_topbar_static_text')->toHtml(); ?> 	
			</div>
		</div>
	</div>
	<?php } ?>
	<div class="sticky-header">
		<div class="header_middle header_padding container gx-4 flex-layout space-between center_vertical flex-nowrap pt-xl-4 mt-xl-3">
			<div class="col_left flex-layout center_vertical">
				<div class="container-setting-language-currency d-none d-xl-block me-xl-4">
					<?php echo $this->getChildHtml("store_language"); ?>  
					<?php echo $this->getChildHtml("currency"); ?> 
				</div>	
				<?php echo $this->getChildHtml("rokan-search-autocomplete");?>
			</div>
			<div class="header__logo logo-container">
				<?php echo $this->getChildHtml('logo'); ?>
			</div>
			<div class="header__action col_right flex-layout flex-end flex-nowrap">
				<div class="flex-layout center_vertical flex-end flex-nowrap">
					<ul class="flex-layout header__action-default center_vertical no-wrap-desktop">
						<li class="account-link-header d-none d-xl-block">
							<?php echo $this->getChildHtml("header.links"); ?>
						</li>
						<?php echo $block->getLayout()->createBlock('Magento\Wishlist\Block\Link')->setTemplate('Magento_Wishlist::link.phtml')->toHtml();?>
						<li class="minicart-li-content-show-hide fixed-minicart">
							<?php echo $this->getChildHtml('minicart'); ?>
						</li>
					</ul>
				</div>
			</div>
		</div>
		<div class="for-full-width-menu blueskytechco-header header_padding pt-xl-4">
			<div class="header__menu text-center">
				<?php echo $this->getChildHtml("horizontal.menu"); ?>
			</div>
		</div>
	</div>
</div>