<div class="header-container layout-9 header_style-3">
	<?php if($block->isEnableTopBar()){ ?>
	<div class="topbar d-none d-md-block border_bottom">
		<div class="topbar__inner flex-layout space-between center_vertical container gx-4">
			<div class="topbar__section">
				<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('default_topbar_static_text')->toHtml(); ?> 
			</div>
			<div class="topbar__section col_right flex-layout center_vertical flex-end">
				<div class="container-setting-language-currency">
					<?php echo $this->getChildHtml("store_language"); ?>  
					<?php echo $this->getChildHtml("currency"); ?> 
				</div>
				<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('default_topbar_social_icon')->toHtml(); ?> 
			</div>
		</div>
	</div>
	<?php } ?>
	<div class="header-content sticky-header blueskytechco-header pt-xl-2 border_bottom">
		<div class="container gx-4">
			<div class="header_middle flex-layout space-between center_vertical header_padding">
				<div class="header__logo logo-container col_left order-1">
					<?php echo $this->getChildHtml('logo'); ?>
				</div>
				<div class="top-search col-xl-6 col-12 order-3 order-xl-2 mt-4 mt-xl-0 mb-2 mb-xl-0">
					<?php echo $this->getChildHtml("rokan-search-autocomplete");?>
				</div>
				<div class="header__action col_right flex-layout flex-end flex-nowrap order-2 order-xl-3">
					<div class="flex-layout center_vertical flex-end flex-nowrap">
						<ul class="flex-layout header__action-default center_vertical no-wrap-desktop">
							<li class="account-link-header d-none d-xl-block">
								<?php echo $this->getChildHtml("header.links"); ?>
							</li>
							<li class="minicart-li-content-show-hide fixed-minicart">
								<?php echo $this->getChildHtml('minicart'); ?>
							</li>
							<?php if(!$block->isEnableTopBar()){ ?>
								<li class="setting-view d-none">
									<label for="modal-mobile-input">
										<svg width="20px" height="20px" fill="currentColor" stroke="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
											<path d="M442 114H6a6 6 0 0 1-6-6V84a6 6 0 0 1 6-6h436a6 6 0 0 1 6 6v24a6 6 0 0 1-6 6zm0 160H6a6 6 0 0 1-6-6v-24a6 6 0 0 1 6-6h436a6 6 0 0 1 6 6v24a6 6 0 0 1-6 6zm0 160H6a6 6 0 0 1-6-6v-24a6 6 0 0 1 6-6h436a6 6 0 0 1 6 6v24a6 6 0 0 1-6 6z"></path>
										</svg>
									</label>
								</li>
							<?php } ?>
						</ul>
					</div>
				</div>
			</div>
		</div>
		<div class="header__menu col_left for-full-width-menu border_top vertical-hozital-menu">
			<div class="container gx-4">
				<div class="flex-layout center_vertical no-wrap-desktop">
					<div class="col_left vertical-menu">
						<?php echo $this->getChildHtml("vertical.menu"); ?>
					</div>				
					<div class=" horizontal-menu text-center col-xl-7">
						<?php echo $this->getChildHtml("horizontal.menu"); ?>
					</div>
					<div class="col-xl-2">
					</div>
				</div>
			</div>
		</div>
	</div>	
</div>
<!-- header setting modal -->
<?php if(!$block->isEnableTopBar()){ ?>
	<div class="header__setting--modal">
		<input type="checkbox" hidden class="modal_input" name="s" id="modal-mobile-input">
		<label for="modal-mobile-input" class="nav_overlay "></label>
		<div class="header__setting">
			<div class="settings-head">
			<label for="modal-mobile-input" class="settings-close"><span class="action close no-shadow"></span></label>
			</div>
			<div class="settings-inner">
				<?php echo $this->getChildHtml("store_language"); ?>
				<?php echo $this->getChildHtml("currency"); ?>
			</div>
		</div>
	</div>
<?php } ?>