<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post view template
 *
 * @var $block \Magefan\Blog\Block\Post\View
 */
?>
<?php
    $_post = $block->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postName = $block->escapeHtml($_post->getTitle(), null);
?>
<div class="post-view">
    <div class="post-holder post-holder-<?= (int)$_post->getId() ?>">
        <div class="post-header">
            <div class="category-comment">
                <?php if ($_categoriesCount = $_post->getCategoriesCount()) { ?>
                    <div class="item post-categories">
                        <?php $n = 0; ?>
                        <?php foreach ($_post->getParentCategories() as $ct) { ?>
                            <?php $n++; ?>
                            <a title="<?= $block->escapeHtml($ct->getTitle()) ?>"
                                href="<?= $block->escapeUrl($ct->getCategoryUrl()) ?>"
                            ><?= $block->escapeHtml($ct->getTitle()) ?></a>
                        <?php } ?>
                    </div>
                <?php } ?>
            </div>
            <h1 class="post-title"><?php echo $_post->getTitle(); ?></h1>
            <div class="post-info">
                <?php if ($block->authorEnabled()) { ?>
                    <?php if ($_author = $_post->getAuthor()) { ?>
                    <div class="item post-author">
                            <span class="label"><?= $block->escapeHtml(__('By')) ?></span>
                            <span class="value">
                            <?php if ($authorPageEnabled = $block->authorPageEnabled()) { ?>
                            <a title="<?= $block->escapeHtml($_author->getTitle()) ?>"
                            href="<?= $block->escapeUrl($_author->getAuthorUrl()) ?>">
                            <?php } ?>

                            <?= $block->escapeHtml($_author->getTitle()) ?>

                            <?php if ($authorPageEnabled) { ?>
                            </a>
                            <?php } ?>
                        </span>
                    </div>
                    <?php } ?>
                <?php } ?>
                <?php if ($_post->isPublishDateEnabled()) { ?> 
                    <div class="item post-date">
                        <span class="label"><?= $block->escapeHtml(__('on')) ?></span>
                        <span class="value"><?= $block->escapeHtml($_post->getPublishDate()) ?></span>
                    </div>
                <?php } ?>
            </div>
        </div>
        <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
                    <?php
                    $featuredImgAlt = $_post->getData('featured_img_alt');
                    if (!$featuredImgAlt) {
                        $featuredImgAlt = $_postName;
                    }
                    ?>
                    <div class="post-ftimg-hld">
                        <img src="<?= $block->escapeUrl($featuredImage) ?>"
                             alt="<?= $block->escapeHtml($featuredImgAlt) ?>" />
                    </div>
                <?php } ?>
        <div class="post-content">
            <div class="post-description clearfix">
                <div class="post-text-hld">
                    <?= /*@noEscape*/ $block->getContent() ?>
                    <div class="clear clearfix"></div>
                </div>
            </div>
        </div>
        <div class="post-infor-bottom border_bottom d-flex align-items-center justify-content-between">
            <div class="post-tag-comment">
                <?php if ($_tagsCount = $_post->getTagsCount()) { ?>
                    <div class="item post-tags">
                    <span class="label"><?= $block->escapeHtml(__('Tag:')) ?></span>
                        <?php $n = 0; ?>
                        <?php foreach ($_post->getRelatedTags() as $tag) { ?>
                            <?php $n++; ?>
                            <a title="<?= $block->escapeHtml($tag->getTitle()) ?>"
                            href="<?= $block->escapeUrl($tag->getTagUrl()) ?>"
                            ><?= $block->escapeHtml($tag->getTitle()) ?></a><?= ($n != $_tagsCount) ? ',' : '' ?>
                        <?php } ?>
                    </div>
                <?php } ?>
            </div>    
            <div class="addthis_toolbox addthis_default_style d-flex align-items-center" addthis:url="<?= $block->escapeUrl($_postUrl) ?>">
                <span class="label"><?= $block->escapeHtml(__('Share:')) ?></span>
                <a class="addthis_button_facebook"></a>
                <a class="addthis_button_twitter"></a>
                <a class="addthis_button_email"></a>
                <a class="addthis_button_compact"></a>
            </div>
        </div>
    </div>
    <div class="post-bottom">
        <?= $block->getChildHtml('blog.post.bottom') ?>
    </div>
</div>